CREATE DATABASE SITEMERCADO
GO
USE SITEMERCADO;
GO
CREATE TABLE PRODUTO(
ID INT NOT NULL IDENTITY PRIMARY KEY,
NOME VARCHAR(80) NOT NULL,
VALORVENDA DECIMAL(24,9),
IMAGEM varbinary(max)
)
GO
